// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'bn'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​v​e​l​t​e​K​i​t​ ​S​t​a​c​k​t​e​r
	 */
	appName: string
	/**
	 * S​v​e​l​t​e​K​i​t​ ​S​t​a​c​k​t​e​r​ ​-​ ​A​n​ ​a​w​e​s​o​m​e​ ​S​v​e​l​t​e​k​i​t​ ​P​r​o​d​u​c​t​i​o​n​ ​r​e​a​d​y​ ​s​t​a​r​t​e​r​ ​t​e​m​p​l​a​t​e
	 */
	title: string
	/**
	 * S​v​e​l​t​e​K​i​t​ ​S​t​a​c​k​t​e​r​ ​i​s​ ​a​ ​p​r​o​d​u​c​t​i​o​n​ ​r​e​a​d​y​ ​s​t​a​r​t​e​r​ ​t​e​m​p​l​a​t​e​ ​f​o​r​ ​S​v​e​l​t​e​k​i​t​.​ ​D​i​s​c​o​v​e​r​ ​t​h​i​s​ ​i​n​c​r​e​d​i​b​l​e​ ​S​v​e​l​t​e​K​i​t​ ​p​r​o​d​u​c​t​i​o​n​-​r​e​a​d​y​ ​s​t​a​r​t​e​r​ ​t​e​m​p​l​a​t​e​ ​f​e​a​t​u​r​i​n​g​ ​T​a​i​l​w​i​n​d​ ​C​S​S​,​ ​t​h​e​ ​s​h​a​d​c​n​-​s​v​e​l​t​e​ ​U​I​ ​l​i​b​r​a​r​y​,​ ​S​u​p​e​r​f​o​r​m​ ​+​ ​F​o​r​m​s​n​a​p​,​ ​t​y​p​e​-​s​a​f​e​ ​i​1​8​n​,​ ​S​E​O​,​ ​L​o​t​t​i​e​ ​a​n​i​m​a​t​i​o​n​s​,​ ​a​n​ ​I​m​a​g​e​ ​c​o​m​p​o​n​e​n​t​,​ ​a​n​d​ ​m​u​c​h​ ​m​o​r​e​.​ ​W​i​t​h​ ​t​h​i​s​ ​t​e​m​p​l​a​t​e​,​ ​y​o​u​ ​c​a​n​ ​b​y​p​a​s​s​ ​t​h​e​ ​s​e​t​u​p​ ​h​a​s​s​l​e​ ​a​n​d​ ​c​o​n​c​e​n​t​r​a​t​e​ ​o​n​ ​t​r​a​n​s​f​o​r​m​i​n​g​ ​y​o​u​r​ ​d​r​e​a​m​s​ ​i​n​t​o​ ​r​e​a​l​i​t​y​.
	 */
	description: string
	/**
	 * s​v​e​l​t​e​k​i​t​ ​s​t​a​r​t​e​r​ ​t​e​m​p​l​a​t​e​,​ ​t​a​i​l​w​i​n​d​ ​c​s​s​,​ ​s​h​a​d​c​n​ ​s​v​e​l​t​e​,​ ​s​u​p​e​r​f​o​r​m​,​ ​f​o​r​m​s​n​a​p​,​ ​t​y​p​e​s​a​f​e​ ​i​1​8​n​,​ ​l​o​t​t​i​e​ ​a​n​i​m​a​t​i​o​n​,​ ​i​m​a​g​e​ ​c​o​m​p​o​n​e​n​t​ ​h​u​s​k​y​,​ ​t​y​p​e​s​c​r​i​p​t​,​ ​v​i​t​e​,​ ​S​v​e​l​t​e​K​i​t​ ​S​t​a​c​k​t​e​r
	 */
	keywords: string
	/**
	 * @​s​h​a​m​s​c​o​r​n​e​r
	 */
	appTwitterAccount: string
	common: {
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * L​o​g​o​u​t
		 */
		logout: string
		/**
		 * S​i​g​n​ ​u​p
		 */
		signup: string
		/**
		 * S​h​o​w
		 */
		show: string
		/**
		 * H​i​d​e
		 */
		hide: string
		/**
		 * O​r
		 */
		or: string
		/**
		 * T​o​g​g​l​e​ ​t​h​e​m​e
		 */
		toggleTheme: string
		/**
		 * C​l​o​s​e
		 */
		close: string
	}
	appLogo: {
		/**
		 * S​v​e​l​t​e​K​i​t​ ​S​t​a​c​k​t​e​r​ ​i​s​ ​a​ ​p​r​o​d​u​c​t​i​o​n​ ​r​e​a​d​y​ ​s​t​a​r​t​e​r​ ​t​e​m​p​l​a​t​e​ ​f​o​r​ ​S​v​e​l​t​e​k​i​t​.​ ​D​i​s​c​o​v​e​r​ ​t​h​i​s​ ​i​n​c​r​e​d​i​b​l​e​ ​S​v​e​l​t​e​K​i​t​ ​p​r​o​d​u​c​t​i​o​n​-​r​e​a​d​y​ ​s​t​a​r​t​e​r​ ​t​e​m​p​l​a​t​e​ ​f​e​a​t​u​r​i​n​g​ ​T​a​i​l​w​i​n​d​ ​C​S​S​,​ ​t​h​e​ ​s​h​a​d​c​n​-​s​v​e​l​t​e​ ​U​I​ ​l​i​b​r​a​r​y​,​ ​S​u​p​e​r​f​o​r​m​ ​+​ ​F​o​r​m​s​n​a​p​,​ ​t​y​p​e​-​s​a​f​e​ ​i​1​8​n​,​ ​S​E​O​,​ ​L​o​t​t​i​e​ ​a​n​i​m​a​t​i​o​n​s​,​ ​a​n​ ​I​m​a​g​e​ ​c​o​m​p​o​n​e​n​t​,​ ​a​n​d​ ​m​u​c​h​ ​m​o​r​e​.​ ​W​i​t​h​ ​t​h​i​s​ ​t​e​m​p​l​a​t​e​,​ ​y​o​u​ ​c​a​n​ ​b​y​p​a​s​s​ ​t​h​e​ ​s​e​t​u​p​ ​h​a​s​s​l​e​ ​a​n​d​ ​c​o​n​c​e​n​t​r​a​t​e​ ​o​n​ ​t​r​a​n​s​f​o​r​m​i​n​g​ ​y​o​u​r​ ​d​r​e​a​m​s​ ​i​n​t​o​ ​r​e​a​l​i​t​y​.
		 */
		hrefTitle: string
		/**
		 * S​v​e​l​t​e​K​i​t​ ​S​t​a​c​k​t​e​r​ ​L​o​g​o
		 */
		alt: string
	}
	schemaMarkup: {
		/**
		 * C​o​r​p​o​r​a​t​i​o​n
		 */
		type: string
		/**
		 * M​e​m​o​w​i​s​e​ ​I​n​c​.
		 */
		name: string
		/**
		 * M​e​m​o​w​i​s​e​ ​i​s​ ​a​ ​s​o​f​t​w​a​r​e​ ​c​o​m​p​a​n​y​ ​t​h​a​t​ ​b​u​i​l​d​s​ ​p​r​o​d​u​c​t​s​ ​t​o​ ​h​e​l​p​ ​p​e​o​p​l​e​.​ ​W​e​ ​a​r​e​ ​a​ ​s​m​a​l​l​ ​t​e​a​m​ ​o​f​ ​p​a​s​s​i​o​n​a​t​e​ ​d​e​v​e​l​o​p​e​r​s​,​ ​d​e​s​i​g​n​e​r​s​,​ ​a​n​d​ ​e​n​t​r​e​p​r​e​n​e​u​r​s​.​ ​W​e​ ​a​r​e​ ​b​a​s​e​d​ ​i​n​ ​D​h​a​k​a​,​ ​B​a​n​g​l​a​d​e​s​h​.
		 */
		markupDescription: string
		founder: {
			'0': {
				/**
				 * P​e​r​s​o​n
				 */
				type: string
				/**
				 * S​h​a​m​i​m​ ​H​o​s​s​a​i​n
				 */
				name: string
			}
			'1': {
				/**
				 * P​e​r​s​o​n
				 */
				type: string
				/**
				 * M​a​s​u​d​ ​R​a​n​a
				 */
				name: string
			}
			'2': {
				/**
				 * P​e​r​s​o​n
				 */
				type: string
				/**
				 * S​h​a​d​m​a​n​ ​N​a​s​i​f
				 */
				name: string
			}
		}
		/**
		 * 2​0​2​3​-​1​0​-​0​2
		 */
		foundingDate: string
		contactPoint: {
			'0': {
				/**
				 * C​o​n​t​a​c​t​P​o​i​n​t
				 */
				type: string
				/**
				 * m​e​m​o​w​i​s​e​i​n​c​@​g​m​a​i​l​.​c​o​m
				 */
				email: string
				telephone: string
				/**
				 * c​u​s​t​o​m​e​r​ ​s​e​r​v​i​c​e
				 */
				contactType: string
			}
		}
	}
	errorPage: {
		/**
		 * 4​0​4
		 */
		title: string
		/**
		 * N​o​t​ ​f​o​u​n​d
		 */
		subtitle: string
		/**
		 * 4​0​4
		 */
		pageTitle: string
		/**
		 * L​o​o​k​i​n​g​ ​f​o​r​ ​h​e​l​p​?​ ​R​e​a​c​h​ ​o​u​t​ ​t​o​ ​u​s​ ​a​t​ ​s​u​p​p​o​r​t​@​a​p​p​d​o​m​a​i​n​.​c​o​m
		 */
		description: string
		/**
		 * S​u​p​p​o​r​t​,​ ​C​o​n​t​a​c​t​,​ ​H​e​l​p​,​ ​4​0​4​,​ ​N​o​t​ ​f​o​u​n​d
		 */
		keywords: string
	}
	homepage: {
		/**
		 * A​ ​p​r​o​d​u​c​t​i​o​n​ ​r​e​a​d​y​ ​s​t​a​r​t​e​r​ ​t​e​m​p​l​a​t​e​ ​f​o​r​ ​S​v​e​l​t​e​K​i​t​.
		 */
		title: string
		/**
		 * S​v​e​l​t​e​K​i​t​ ​S​t​a​c​k​t​e​r​ ​i​s​ ​a​ ​p​r​o​d​u​c​t​i​o​n​ ​r​e​a​d​y​ ​s​t​a​r​t​e​r​ ​t​e​m​p​l​a​t​e​ ​f​o​r​ ​S​v​e​l​t​e​k​i​t​.​ ​D​i​s​c​o​v​e​r​ ​t​h​i​s​ ​i​n​c​r​e​d​i​b​l​e​ ​S​v​e​l​t​e​K​i​t​ ​p​r​o​d​u​c​t​i​o​n​-​r​e​a​d​y​ ​s​t​a​r​t​e​r​ ​t​e​m​p​l​a​t​e​ ​f​e​a​t​u​r​i​n​g​ ​T​a​i​l​w​i​n​d​ ​C​S​S​,​ ​t​h​e​ ​s​h​a​d​c​n​-​s​v​e​l​t​e​ ​U​I​ ​l​i​b​r​a​r​y​,​ ​S​u​p​e​r​f​o​r​m​ ​+​ ​F​o​r​m​s​n​a​p​,​ ​t​y​p​e​-​s​a​f​e​ ​i​1​8​n​,​ ​S​E​O​,​ ​L​o​t​t​i​e​ ​a​n​i​m​a​t​i​o​n​s​,​ ​a​n​ ​I​m​a​g​e​ ​c​o​m​p​o​n​e​n​t​,​ ​a​n​d​ ​m​u​c​h​ ​m​o​r​e​.​ ​W​i​t​h​ ​t​h​i​s​ ​t​e​m​p​l​a​t​e​,​ ​y​o​u​ ​c​a​n​ ​b​y​p​a​s​s​ ​t​h​e​ ​s​e​t​u​p​ ​h​a​s​s​l​e​ ​a​n​d​ ​c​o​n​c​e​n​t​r​a​t​e​ ​o​n​ ​t​r​a​n​s​f​o​r​m​i​n​g​ ​y​o​u​r​ ​d​r​e​a​m​s​ ​i​n​t​o​ ​r​e​a​l​i​t​y​.
		 */
		subtitle: string
		/**
		 * F​e​a​t​u​r​e​s
		 */
		features: string
		/**
		 * C​h​e​c​k​ ​f​o​r​m​ ​s​u​b​m​i​s​s​i​o​n​ ​d​e​m​o
		 */
		checkFormSubmission: string
		/**
		 * G​o​ ​t​o​ ​l​o​g​i​n​ ​p​a​g​e
		 */
		goToLogin: string
		/**
		 * E​m​o​j​i​ ​p​i​c​k​e​r
		 */
		emojiPicker: string
		/**
		 * C​h​e​c​k​ ​G​i​t​h​u​b​ ​R​e​p​o
		 */
		checkGithub: string
	}
	loginPage: {
		/**
		 * W​e​l​c​o​m​e​ ​b​a​c​k​!
		 */
		title: string
		/**
		 * L​o​g​ ​i​n
		 */
		pageTitle: string
		/**
		 * L​o​g​i​n​ ​t​o​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​a​n​d​ ​e​x​p​e​r​i​e​n​c​e​ ​l​e​a​r​n​i​n​g​ ​t​h​a​t​ ​y​o​u​ ​h​a​v​e​ ​n​e​v​e​r​ ​e​x​p​e​r​i​e​n​c​e​d​ ​b​e​f​o​r​e​.
		 */
		description: string
		/**
		 * L​o​g​i​n​,​ ​S​i​g​n​ ​i​n​,​ ​L​o​g​ ​i​n​,​ ​S​i​g​n​ ​u​p​,​ ​R​e​g​i​s​t​e​r
		 */
		keywords: string
		form: {
			/**
			 * E​m​a​i​l
			 */
			email: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			password: string
			/**
			 * L​o​g​ ​i​n
			 */
			submit: string
			/**
			 * O​r​ ​c​o​n​t​i​n​u​e​ ​w​i​t​h
			 */
			continueWith: string
			/**
			 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
			 */
			dontHaveAccount: string
			/**
			 * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d​?
			 */
			forgotPassword: string
			/**
			 * R​e​m​e​m​b​e​r​ ​m​e​?
			 */
			rememberMe: string
		}
	}
	registerPage: {
		/**
		 * L​e​t​'​s​ ​d​o​ ​a​w​e​s​o​m​e​!
		 */
		title: string
		/**
		 * R​e​g​i​s​t​e​r
		 */
		pageTitle: string
		/**
		 * C​r​e​a​t​e​ ​a​n​ ​a​c​c​o​u​n​t​ ​a​n​d​ ​e​x​p​e​r​i​e​n​c​e​ ​l​e​a​r​n​i​n​g​ ​t​h​a​t​ ​y​o​u​ ​h​a​v​e​ ​n​e​v​e​r​ ​e​x​p​e​r​i​e​n​c​e​d​ ​b​e​f​o​r​e​.
		 */
		description: string
		/**
		 * L​o​g​i​n​,​ ​S​i​g​n​ ​i​n​,​ ​L​o​g​ ​i​n​,​ ​S​i​g​n​ ​u​p​,​ ​R​e​g​i​s​t​e​r
		 */
		keywords: string
		form: {
			/**
			 * N​a​m​e
			 */
			name: string
			/**
			 * E​m​a​i​l
			 */
			email: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			password: string
			/**
			 * R​e​g​i​s​t​e​r
			 */
			submit: string
			/**
			 * O​r​ ​c​o​n​t​i​n​u​e​ ​w​i​t​h
			 */
			continueWith: string
			/**
			 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
			 */
			alreadyHaveAccount: string
		}
		successfulRegistration: {
			/**
			 * R​e​g​i​s​t​r​a​t​i​o​n​ ​s​u​c​c​e​s​s​f​u​l​!
			 */
			title: string
			/**
			 * Y​o​u​ ​h​a​v​e​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​r​e​g​i​s​t​e​r​e​d​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​e​m​a​i​l​ ​t​o​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​a​c​c​o​u​n​t​.
			 */
			description: string
			/**
			 * H​a​v​e​n​'​t​ ​r​e​c​e​i​v​e​d​ ​t​h​e​ ​e​m​a​i​l​?​ ​C​l​i​c​k​ ​t​h​e​ ​r​e​s​e​n​d​ ​b​u​t​t​o​n​ ​b​e​l​o​w​.
			 */
			haveNotGetEmail: string
			/**
			 * R​e​s​e​n​d​ ​e​m​a​i​l
			 */
			resendEmail: string
			/**
			 * E​m​a​i​l​ ​r​e​s​e​n​t​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			emailResentSuccessfully: string
		}
	}
	forgotPasswordPage: {
		/**
		 * F​o​r​g​o​t​ ​P​a​s​s​w​o​r​d​!
		 */
		title: string
		/**
		 * F​o​r​g​o​t​ ​P​a​s​s​w​o​r​d
		 */
		pageTitle: string
		/**
		 * F​o​r​g​o​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​?​ ​N​o​ ​w​o​r​r​i​e​s​!​ ​E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​ ​a​n​d​ ​w​e​ ​w​i​l​l​ ​s​e​n​d​ ​y​o​u​ ​a​ ​l​i​n​k​ ​t​o​ ​r​e​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​.
		 */
		description: string
		/**
		 * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d​,​ ​R​e​s​e​t​ ​p​a​s​s​w​o​r​d​,​ ​P​a​s​s​w​o​r​d​ ​r​e​c​o​v​e​r​y
		 */
		keywords: string
		form: {
			/**
			 * E​m​a​i​l
			 */
			email: string
			/**
			 * S​u​b​m​i​t
			 */
			submit: string
			/**
			 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
			 */
			dontHaveAccount: string
			/**
			 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
			 */
			alreadyHaveAccount: string
		}
		successfulPasswordResetSent: {
			/**
			 * P​a​s​s​w​o​r​d​ ​r​e​s​e​t​ ​e​m​a​i​l​ ​s​e​n​t​!
			 */
			title: string
			/**
			 * A​n​ ​e​m​a​i​l​ ​h​a​s​ ​b​e​e​n​ ​s​e​n​t​ ​t​o​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​e​m​a​i​l​ ​t​o​ ​r​e​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​.
			 */
			description: string
		}
	}
	errors: {
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
		 */
		somethingWentWrong: string
	}
}

export type TranslationFunctions = {
	/**
	 * SvelteKit Stackter
	 */
	appName: () => LocalizedString
	/**
	 * SvelteKit Stackter - An awesome Sveltekit Production ready starter template
	 */
	title: () => LocalizedString
	/**
	 * SvelteKit Stackter is a production ready starter template for Sveltekit. Discover this incredible SvelteKit production-ready starter template featuring Tailwind CSS, the shadcn-svelte UI library, Superform + Formsnap, type-safe i18n, SEO, Lottie animations, an Image component, and much more. With this template, you can bypass the setup hassle and concentrate on transforming your dreams into reality.
	 */
	description: () => LocalizedString
	/**
	 * sveltekit starter template, tailwind css, shadcn svelte, superform, formsnap, typesafe i18n, lottie animation, image component husky, typescript, vite, SvelteKit Stackter
	 */
	keywords: () => LocalizedString
	/**
	 * @shamscorner
	 */
	appTwitterAccount: () => LocalizedString
	common: {
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Logout
		 */
		logout: () => LocalizedString
		/**
		 * Sign up
		 */
		signup: () => LocalizedString
		/**
		 * Show
		 */
		show: () => LocalizedString
		/**
		 * Hide
		 */
		hide: () => LocalizedString
		/**
		 * Or
		 */
		or: () => LocalizedString
		/**
		 * Toggle theme
		 */
		toggleTheme: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
	}
	appLogo: {
		/**
		 * SvelteKit Stackter is a production ready starter template for Sveltekit. Discover this incredible SvelteKit production-ready starter template featuring Tailwind CSS, the shadcn-svelte UI library, Superform + Formsnap, type-safe i18n, SEO, Lottie animations, an Image component, and much more. With this template, you can bypass the setup hassle and concentrate on transforming your dreams into reality.
		 */
		hrefTitle: () => LocalizedString
		/**
		 * SvelteKit Stackter Logo
		 */
		alt: () => LocalizedString
	}
	schemaMarkup: {
		/**
		 * Corporation
		 */
		type: () => LocalizedString
		/**
		 * Memowise Inc.
		 */
		name: () => LocalizedString
		/**
		 * Memowise is a software company that builds products to help people. We are a small team of passionate developers, designers, and entrepreneurs. We are based in Dhaka, Bangladesh.
		 */
		markupDescription: () => LocalizedString
		founder: {
			'0': {
				/**
				 * Person
				 */
				type: () => LocalizedString
				/**
				 * Shamim Hossain
				 */
				name: () => LocalizedString
			}
			'1': {
				/**
				 * Person
				 */
				type: () => LocalizedString
				/**
				 * Masud Rana
				 */
				name: () => LocalizedString
			}
			'2': {
				/**
				 * Person
				 */
				type: () => LocalizedString
				/**
				 * Shadman Nasif
				 */
				name: () => LocalizedString
			}
		}
		/**
		 * 2023-10-02
		 */
		foundingDate: () => LocalizedString
		contactPoint: {
			'0': {
				/**
				 * ContactPoint
				 */
				type: () => LocalizedString
				/**
				 * memowiseinc@gmail.com
				 */
				email: () => LocalizedString
				telephone: () => LocalizedString
				/**
				 * customer service
				 */
				contactType: () => LocalizedString
			}
		}
	}
	errorPage: {
		/**
		 * 404
		 */
		title: () => LocalizedString
		/**
		 * Not found
		 */
		subtitle: () => LocalizedString
		/**
		 * 404
		 */
		pageTitle: () => LocalizedString
		/**
		 * Looking for help? Reach out to us at support@appdomain.com
		 */
		description: () => LocalizedString
		/**
		 * Support, Contact, Help, 404, Not found
		 */
		keywords: () => LocalizedString
	}
	homepage: {
		/**
		 * A production ready starter template for SvelteKit.
		 */
		title: () => LocalizedString
		/**
		 * SvelteKit Stackter is a production ready starter template for Sveltekit. Discover this incredible SvelteKit production-ready starter template featuring Tailwind CSS, the shadcn-svelte UI library, Superform + Formsnap, type-safe i18n, SEO, Lottie animations, an Image component, and much more. With this template, you can bypass the setup hassle and concentrate on transforming your dreams into reality.
		 */
		subtitle: () => LocalizedString
		/**
		 * Features
		 */
		features: () => LocalizedString
		/**
		 * Check form submission demo
		 */
		checkFormSubmission: () => LocalizedString
		/**
		 * Go to login page
		 */
		goToLogin: () => LocalizedString
		/**
		 * Emoji picker
		 */
		emojiPicker: () => LocalizedString
		/**
		 * Check Github Repo
		 */
		checkGithub: () => LocalizedString
	}
	loginPage: {
		/**
		 * Welcome back!
		 */
		title: () => LocalizedString
		/**
		 * Log in
		 */
		pageTitle: () => LocalizedString
		/**
		 * Login to your account and experience learning that you have never experienced before.
		 */
		description: () => LocalizedString
		/**
		 * Login, Sign in, Log in, Sign up, Register
		 */
		keywords: () => LocalizedString
		form: {
			/**
			 * Email
			 */
			email: () => LocalizedString
			/**
			 * Password
			 */
			password: () => LocalizedString
			/**
			 * Log in
			 */
			submit: () => LocalizedString
			/**
			 * Or continue with
			 */
			continueWith: () => LocalizedString
			/**
			 * Don't have an account?
			 */
			dontHaveAccount: () => LocalizedString
			/**
			 * Forgot password?
			 */
			forgotPassword: () => LocalizedString
			/**
			 * Remember me?
			 */
			rememberMe: () => LocalizedString
		}
	}
	registerPage: {
		/**
		 * Let's do awesome!
		 */
		title: () => LocalizedString
		/**
		 * Register
		 */
		pageTitle: () => LocalizedString
		/**
		 * Create an account and experience learning that you have never experienced before.
		 */
		description: () => LocalizedString
		/**
		 * Login, Sign in, Log in, Sign up, Register
		 */
		keywords: () => LocalizedString
		form: {
			/**
			 * Name
			 */
			name: () => LocalizedString
			/**
			 * Email
			 */
			email: () => LocalizedString
			/**
			 * Password
			 */
			password: () => LocalizedString
			/**
			 * Register
			 */
			submit: () => LocalizedString
			/**
			 * Or continue with
			 */
			continueWith: () => LocalizedString
			/**
			 * Already have an account?
			 */
			alreadyHaveAccount: () => LocalizedString
		}
		successfulRegistration: {
			/**
			 * Registration successful!
			 */
			title: () => LocalizedString
			/**
			 * You have successfully registered. Please check your email to verify your account.
			 */
			description: () => LocalizedString
			/**
			 * Haven't received the email? Click the resend button below.
			 */
			haveNotGetEmail: () => LocalizedString
			/**
			 * Resend email
			 */
			resendEmail: () => LocalizedString
			/**
			 * Email resent successfully!
			 */
			emailResentSuccessfully: () => LocalizedString
		}
	}
	forgotPasswordPage: {
		/**
		 * Forgot Password!
		 */
		title: () => LocalizedString
		/**
		 * Forgot Password
		 */
		pageTitle: () => LocalizedString
		/**
		 * Forgot your password? No worries! Enter your email address and we will send you a link to reset your password.
		 */
		description: () => LocalizedString
		/**
		 * Forgot password, Reset password, Password recovery
		 */
		keywords: () => LocalizedString
		form: {
			/**
			 * Email
			 */
			email: () => LocalizedString
			/**
			 * Submit
			 */
			submit: () => LocalizedString
			/**
			 * Don't have an account?
			 */
			dontHaveAccount: () => LocalizedString
			/**
			 * Already have an account?
			 */
			alreadyHaveAccount: () => LocalizedString
		}
		successfulPasswordResetSent: {
			/**
			 * Password reset email sent!
			 */
			title: () => LocalizedString
			/**
			 * An email has been sent to your email address. Please check your email to reset your password.
			 */
			description: () => LocalizedString
		}
	}
	errors: {
		/**
		 * Something went wrong
		 */
		somethingWentWrong: () => LocalizedString
	}
}

export type Formatters = {}
